version: '3.8'

services:
  gridbnb-bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gridbnb-bot
    restart: always
    ports:
      - "58181:58181" # 如果需要开放端口，请根据需要修改
    volumes:
      - /DATA/AppData/gridbnb/app:/app
